# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

from gRPC import RobotService_pb2 as proto_dot_RobotService__pb2

GRPC_GENERATED_VERSION = '1.76.0'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + ' but the generated code in proto/RobotService_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class RobotServiceStub(object):
    """服务定义
    """

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.clientUpload = channel.stream_stream(
                '/RobotService/clientUpload',
                request_serializer=proto_dot_RobotService__pb2.RobotUploadRequest.SerializeToString,
                response_deserializer=proto_dot_RobotService__pb2.RobotUploadResponse.FromString,
                _registered_method=True)
        self.serverCommand = channel.stream_stream(
                '/RobotService/serverCommand',
                request_serializer=proto_dot_RobotService__pb2.ServerCmdRequest.SerializeToString,
                response_deserializer=proto_dot_RobotService__pb2.ServerCmdResponse.FromString,
                _registered_method=True)


class RobotServiceServicer(object):
    """服务定义
    """

    def clientUpload(self, request_iterator, context):
        """双向流式通信: 上传机器人状态、设备数据、环境数据、到达服务点位数据
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def serverCommand(self, request_iterator, context):
        """双向流式通信: 推送任务分配、服务指令
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_RobotServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'clientUpload': grpc.stream_stream_rpc_method_handler(
                    servicer.clientUpload,
                    request_deserializer=proto_dot_RobotService__pb2.RobotUploadRequest.FromString,
                    response_serializer=proto_dot_RobotService__pb2.RobotUploadResponse.SerializeToString,
            ),
            'serverCommand': grpc.stream_stream_rpc_method_handler(
                    servicer.serverCommand,
                    request_deserializer=proto_dot_RobotService__pb2.ServerCmdRequest.FromString,
                    response_serializer=proto_dot_RobotService__pb2.ServerCmdResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'RobotService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('RobotService', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class RobotService(object):
    """服务定义
    """

    @staticmethod
    def clientUpload(request_iterator,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.stream_stream(
            request_iterator,
            target,
            '/RobotService/clientUpload',
            proto_dot_RobotService__pb2.RobotUploadRequest.SerializeToString,
            proto_dot_RobotService__pb2.RobotUploadResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def serverCommand(request_iterator,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.stream_stream(
            request_iterator,
            target,
            '/RobotService/serverCommand',
            proto_dot_RobotService__pb2.ServerCmdRequest.SerializeToString,
            proto_dot_RobotService__pb2.ServerCmdResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
